//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductManagement.Shared.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assign a nurse to the order.
        /// </summary>
        public static string AssignNurse {
            get {
                return ResourceManager.GetString("AssignNurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Password and the Confirmation Password don&apos;t match.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters, one uppercase letter, one lowercase letter, one digit, and one special character..
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a valid Email Adress.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must contain only English letters without spaces..
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must me greater than 0.
        /// </summary>
        public static string InvalidRangeLabel {
            get {
                return ResourceManager.GetString("InvalidRangeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must contain only English letters without spaces..
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must have atleat 1 item.
        /// </summary>
        public static string Min1 {
            get {
                return ResourceManager.GetString("Min1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min length is 3 characters.
        /// </summary>
        public static string MinLength3 {
            get {
                return ResourceManager.GetString("MinLength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter atleast 1 &apos;{0}&apos;.
        /// </summary>
        public static string MinList1 {
            get {
                return ResourceManager.GetString("MinList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Arabic Characters are required.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only English Characters are required.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 8 or more characters with a mix of letters, numbers &amp; symbols..
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters, one uppercase letter, one lowercase letter, one digit, and one special character..
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Password and the Confirmation Password don&apos;t match.
        /// </summary>
        public static string PasswordCompare {
            get {
                return ResourceManager.GetString("PasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range must be between 1 and 90.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must me greater than 0.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must me greater than 0.
        /// </summary>
        public static string Range_0 {
            get {
                return ResourceManager.GetString("Range>0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter a value between 0 and 100.
        /// </summary>
        public static string Range_0_100 {
            get {
                return ResourceManager.GetString("Range_0-100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; is required.
        /// </summary>
        public static string RequiredLabel {
            get {
                return ResourceManager.GetString("RequiredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 10 characters.
        /// </summary>
        public static string StringLength10 {
            get {
                return ResourceManager.GetString("StringLength10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 100 characters.
        /// </summary>
        public static string StringLength100 {
            get {
                return ResourceManager.GetString("StringLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 1000 characters.
        /// </summary>
        public static string StringLength1000 {
            get {
                return ResourceManager.GetString("StringLength1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 20 characters.
        /// </summary>
        public static string StringLength20 {
            get {
                return ResourceManager.GetString("StringLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 200 characters.
        /// </summary>
        public static string StringLength200 {
            get {
                return ResourceManager.GetString("StringLength200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 250 characters.
        /// </summary>
        public static string StringLength250 {
            get {
                return ResourceManager.GetString("StringLength250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 255 characters.
        /// </summary>
        public static string StringLength255 {
            get {
                return ResourceManager.GetString("StringLength255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 36 characters.
        /// </summary>
        public static string StringLength36 {
            get {
                return ResourceManager.GetString("StringLength36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 4000 characters.
        /// </summary>
        public static string StringLength4000 {
            get {
                return ResourceManager.GetString("StringLength4000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 450 characters.
        /// </summary>
        public static string StringLength450 {
            get {
                return ResourceManager.GetString("StringLength450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 50 characters.
        /// </summary>
        public static string StringLength50 {
            get {
                return ResourceManager.GetString("StringLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Code.
        /// </summary>
        public static string ValidCode {
            get {
                return ResourceManager.GetString("ValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Id Number.
        /// </summary>
        public static string ValidIdNumber {
            get {
                return ResourceManager.GetString("ValidIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Valid {0}.
        /// </summary>
        public static string ValidNumber {
            get {
                return ResourceManager.GetString("ValidNumber", resourceCulture);
            }
        }
    }
}
